### ISSUE TITLE
Cannot read property 'PhysicalResourceId' of undefined

### ISSUE THREAD

**Issue by LuukMoret** [serverless/platform#6]
When publishing to the serverless platform, I get a type error **'Cannot read property 'PhysicalResourceId'** of undefined' on step: **'Serverless: Publishing service to Serverless Platform...'**

This only happens with 2 services (which happen to have a lot of lamba's). I already tried deleting and recreating the complete stack but it doesn't help. Other services deploy with no problem

```
Stack Trace --------------------------------------------

TypeError: Cannot read property 'PhysicalResourceId' of undefined
    at _.forEach (project\node_modules\serverless\lib\plugins\platform\platform.js:303:9)
    at project\node_modules\lodash\lodash.js:4925:15
    at baseForOwn (project\node_modules\lodash\lodash.js:3010:24)
    at project\node_modules\lodash\lodash.js:4894:18
    at Function.forEach (project\node_modules\lodash\lodash.js:9342:14)
    at Platform.getResources (project\node_modules\serverless\lib\plugins\platform\platform.js:301:7)
    at provider.getStackResources.then.then.then.accountId (project\node_modules\serverless\lib\plugins\platform\platform.js:337:27)
From previous event:
    at Platform.publishService (project\node_modules\serverless\lib\plugins\platform\platform.js:326:8)
    at BbPromise.reduce (project\node_modules\serverless\lib\classes\PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (project\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (project\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (project\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (project\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (project\node_modules\serverless\bin\serverless:43:50)
```

**Comment by alexdebrie** [comment]
Hey @LuukMoret, sorry to hear you're having this issue. We've had a few isolated incidents of it.

Thanks for including this information, particularly that it was on a stack with lots of lambdas. I have a hunch on the fix now and will keep you updated.

**Comment by brettswift** [comment]
Same here.  code is erroring at  line 305 in version 1.30
